# ansible/inventory/hosts.yml
all:
  children:
    boutique:
      hosts:
        ec2:
          ansible_host: "{{ lookup('env', 'EC2_HOST') | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      vars:
        ansible_python_interpreter: /usr/bin/python3
